services:
  tda:
    container_name: tda
    build: ./
    ports:
      - 80:80
    restart: always
    environment:
      - DATABASE_ADDRESS=130.61.210.43:8000
    develop:
      watch:
        - action: rebuild
          path: ./requirements.txt
        - action: sync+restart
          path: ./src
          target: /app/src
        - action: sync
          path: ./tests
          target: /app/tests